### ISSUE TITLE
Hi bro, is this efi perfect ? or are there any problems exist?

### ISSUE THREAD

**Issue by zoucao** [R-a-s-c-a-l/Dell-7080MT-Hackintosh#1]

**Comment by Nerders** [comment]
Look at the package structure and config.plist feel a little bit of things.
After MY test, it does not work properly, I guess the author should just start.

In addition, I hope the author can post the configuration information.
@R-a-s-c-a-l, good luck

**Comment by zoucao** [comment]
Hi, @Nerders , I use another EFI to boot my 7080MT+i7+16G+256G+1T the day before yesterday，I found it worked well, if you want to try this, I will share you the EFI.

**Comment by zoucao** [comment]
oh, sry, I found you had used it and picked up an [issue](https://github.com/istarmeow/Hackintosh-Dell.OptiPlex.7080-OpenCore.0.7.0-macOS.Big.Sur.11.4/issues/2), 当我没说。

**Comment by Nerders** [comment]
我发现了一个新的，但是需要PayPal，很糟糕的是我没有信用卡
https://hackintosh.expert/service/dell-optiplex-7080-i7-10700-gt-730-uhd630-download-kext-opencore-big-sur-efi/
